export { StarterKit } from '@tiptap/starter-kit'
export { TextStyle } from '@tiptap/extension-text-style'
export { HorizontalRule } from '@tiptap/extension-horizontal-rule'
export { FocusClasses as Focus } from '@tiptap/extension-focus'
export { Underline } from '@tiptap/extension-underline'
export { FontFamily } from '@tiptap/extension-font-family'
export { Subscript } from '@tiptap/extension-subscript'
export { Superscript } from '@tiptap/extension-superscript'
export { TextAlign } from '@tiptap/extension-text-align'
export { Link } from '@tiptap/extension-link'
export { Placeholder } from '@tiptap/extension-placeholder'
export { Color } from '@tiptap/extension-color'
export { TaskList } from '@tiptap/extension-task-list'
export { TaskItem } from '@tiptap/extension-task-item'
export { Highlight } from '@tiptap/extension-highlight'
export { CharacterCount } from '@tiptap/extension-character-count'

export { Table, TableCell, TableHeader, TableRow } from './table'
export { SlashCommand } from './slash-command'

export * from './extensions'
